// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfgVai1UjWHWfR_6thuOg_D12ogJmGtpU',
    appId: '1:155885730954:web:207996c6e7cddb8dd78173',
    messagingSenderId: '155885730954',
    projectId: 'nba-india-64215',
    authDomain: 'nba-india-64215.firebaseapp.com',
    storageBucket: 'nba-india-64215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4VHgkhbTma0V3skIzHo-jhTlx9Dteihw',
    appId: '1:155885730954:android:203fef1dc59e09d7d78173',
    messagingSenderId: '155885730954',
    projectId: 'nba-india-64215',
    storageBucket: 'nba-india-64215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI04Yt2_ZhGZN0CtQkypm37Zk0FF23kig',
    appId: '1:155885730954:ios:7d250804e46e54a4d78173',
    messagingSenderId: '155885730954',
    projectId: 'nba-india-64215',
    storageBucket: 'nba-india-64215.firebasestorage.app',
    iosBundleId: 'com.example.nba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI04Yt2_ZhGZN0CtQkypm37Zk0FF23kig',
    appId: '1:155885730954:ios:7d250804e46e54a4d78173',
    messagingSenderId: '155885730954',
    projectId: 'nba-india-64215',
    storageBucket: 'nba-india-64215.firebasestorage.app',
    iosBundleId: 'com.example.nba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfgVai1UjWHWfR_6thuOg_D12ogJmGtpU',
    appId: '1:155885730954:web:1949039a19d081a7d78173',
    messagingSenderId: '155885730954',
    projectId: 'nba-india-64215',
    authDomain: 'nba-india-64215.firebaseapp.com',
    storageBucket: 'nba-india-64215.firebasestorage.app',
  );
}
